language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
os: linux
sudo: required
dist: trusty

matrix:
    include:
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: PYVER=py27
        
        - language: generic
          os: osx
          osx_image: xcode8.3
          env: PYVER=py36

# command to install dependencies
install:
  - ./.ci/travis/install.sh
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
# command to run tests
script: 
  - ulimit -n 2048 # Error with py3 and OSX, max file descriptors
  - ./.ci/travis/run.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
