build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"

init:
  - "ECHO %PYTHON%"

install:
  - appveyor DownloadFile "https://heanet.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.3.0/threads-posix/sjlj/x86_64-6.3.0-release-posix-sjlj-rt_v5-rev1.7z"
  - 7z e x86_64-6.3.0-release-posix-sjlj-rt_v5-rev1.7z -oc:\
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\mingw-w64\\bin;%PATH%"
  - "set PYTHONPATH=%PYTHONPATH%;%CD%"
  - "set CONAN_LOGGING_LEVEL=10"
  - "set CONAN_COMPILER=Visual Studio"
  - "set CONAN_COMPILER_VERSION=12"
  - "%PYTHON%/Scripts/pip.exe install -r conans/requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install -r conans/requirements_dev.txt"
  - "%PYTHON%/Scripts/pip.exe install -r conans/requirements_server.txt"


test_script:
  - "dir C:\\mingw-w64\\"
  - "nosetests --with-coverage conans.test"
  
after_test:
  - "codecov"
 
